---
  title: "Synthetic data generation"
subtitle: January-March 2024
author: "Pierre Walthéry"
format: odt
---
Presentation by Dr Venet Osmani (v.osmani@sheffield.ac.uk), 
CA-GAN to create synthetic records, for xample disadvantaged groups; more efficient that machine learning onreal data.
May improve access to real clinical data and advance research.

Example: clinical data from patient with sepsis and hypotension. 
Goal: represent groups from black ethnic minority only.

Evaluation of SD remains an issue. No agreed metric, no consensus about it in the litterature. 
roaches Qualitative (visualisation)
See photos;
QUantitative: distribution distance of the dataset or specific variableS.

Correlation between variables in the datasets; 


Competing objectives:
  privacy protection vs precision/matching with degree of didelity.

-----
  
Presenter Anthony Hughes, compuer science, UoS

Align/ evidence check for social media claim about health impact of treatments.

ie train LLM models to generate synthetic data 

----
Presenter: Mahnaz Arvaneh 
Improving User computer interface.

How computers, roboits, etc can nfer emtional states, etc using brain signals from EEG. 
There are now off the shelves EEG devices.
Proble: lo of noise arising from muscle activity and non related brain activity.
Users are asked to repeat the activity (ie imagine moving a hand) a lot of time.
Lots of data required t; each calibration data requires 20-30 mins;
changes between people, days. More data needed

--> Synthetic data, especially from smaller groups.

------
Presenter: PhD student

Hybrid dataset with mixed of real data vs synthetic data
See ONS six levels of synthetic data(
  
- Crucial issue: bias

---- 
  Other presenter
Travel data of 'bad guys' via PNR data.
How to create synthetic data without accessing the real microdata

Steps:
1- Generate synthetic population (of the whole EU!)
2- Agent based modelling of behaviour

Accounting for household composition, duration of stay, itinerary/routes

-----

Named entity recognition
Ontology ie relationship between objects
llana-->burt > classification andropoodle
huggingface


)
